### ISSUE TITLE
Can't read in hiera values natively

### ISSUE THREAD

**Issue by claflico** [jlambert121/jlambert121-puppet#44]
I've been working with this module for several hours now and have even asked @rnelson0 about it though he says that it is working properly for him. I'm running CentOS 7.2 and Puppet 4.3.1. When I attempt to declare puppet::manage_hiera, puppet::dns_alt_names the module does not read them in so it uses the default values. My other modules such as r10k are able to read in the hieradata natively. 

hieradata/common.yaml
puppet::manage_hiera: false
puppet::dns_alt_names:
  - 'puppet'
  - 'puppet.localdomain'

puppetmaster.pp
    class { '::puppet':
      server  => true,
    }

The above does not work. I've been able to make it work the old way by doing:

hieradata/common.yaml
profile::puppetmaster::manage_hiera: false
profile::puppetmaster::dns_alt_names:
  - 'puppet'
  - 'puppet.localdomain'

puppetmaster.pp
  $dns_alt_names = hiera('profile::puppetmaster::dns_alt_names', undef)
  $manage_hiera = hiera('profile::puppetmaster::manage_hiera', undef)

    class { '::puppet':
      server  => true,
      dns_alt_names => $dns_alt_names,
      manage_hiera  => $manage_hiera,
    }

I've removed all my modules, hieradata, & manifests and stripped it down to just the basics. I have the following procedure I'm using to try and test the module via vagrant:

mkdir puppet
cd puppet
vagrant init puppetlabs/centos-7.2-64-nocm; vagrant up --provider virtualbox

vagrant ssh
sudo yum update -y
sudo reboot

vagrant ssh
sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
sudo yum -y install puppetserver
sudo su
echo "dns_alt_names = puppet,puppet.localdomain" >> /etc/puppetlabs/puppet/puppet.conf
echo "127.0.0.1   puppet puppet.localdomain" >> /etc/hosts
service puppetserver start
exit

sudo su
puppet cert list --all

puppet module install evenup-puppet

echo "---" > /etc/puppetlabs/code/environments/production/hieradata/common.yaml
echo "puppet::runmode: 'service'" >> /etc/puppetlabs/code/environments/production/hieradata/common.yaml
echo "puppet::manage_hiera: false" >> /etc/puppetlabs/code/environments/production/hieradata/common.yaml
echo "puppet::dns_alt_names:" >> /etc/puppetlabs/code/environments/production/hieradata/common.yaml
echo "  - 'puppet'" >> /etc/puppetlabs/code/environments/production/hieradata/common.yaml
echo "  - 'puppet.localdomain'" >> /etc/puppetlabs/code/environments/production/hieradata/common.yaml

echo "class testhiera {" >> /etc/puppetlabs/code/environments/production/manifests/site.pp
echo "  \$test_runmode = hiera('puppet::runmode')" >> /etc/puppetlabs/code/environments/production/manifests/site.pp
echo "  \$test_manage_hiera = hiera('puppet::manage_hiera')" >> /etc/puppetlabs/code/environments/production/manifests/site.pp
echo "  \$test_dns_alt_names = hiera('puppet::dns_alt_names')" >> /etc/puppetlabs/code/environments/production/manifests/site.pp
echo "  notify{\"\${test_runmode}\": }" >> /etc/puppetlabs/code/environments/production/manifests/site.pp
echo "  notify{\"\${test_manage_hiera}\": }" >> /etc/puppetlabs/code/environments/production/manifests/site.pp
echo "  notify{\"\${test_dns_alt_names}\": }" >> /etc/puppetlabs/code/environments/production/manifests/site.pp
echo "}" >> /etc/puppetlabs/code/environments/production/manifests/site.pp
echo "" >> /etc/puppetlabs/code/environments/production/manifests/site.pp
echo "class { 'testhiera': }" >> /etc/puppetlabs/code/environments/production/manifests/site.pp
echo "" >> /etc/puppetlabs/code/environments/production/manifests/site.pp
echo "class { 'puppet':" >> /etc/puppetlabs/code/environments/production/manifests/site.pp
echo "  server  => true," >> /etc/puppetlabs/code/environments/production/manifests/site.pp
echo "}" >> /etc/puppetlabs/code/environments/production/manifests/site.pp

Please take a look and tell me just what the heck it is that I'm doing wrong.

**Comment by claflico** [comment]
Here's an output of my puppet run:

puppet agent --test
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for localhost.localdomain
Info: Applying configuration version '1451536532'
Notice: service
Notice: /Stage[main]/Testhiera/Notify[service]/message: defined 'message' as 'service'
Notice: false
Notice: /Stage[main]/Testhiera/Notify[false]/message: defined 'message' as 'false'
Notice: [puppet, puppet.localdomain]
Notice: /Stage[main]/Testhiera/Notify[[puppet, puppet.localdomain]]/message: defined 'message' as '[puppet, puppet.localdomain]'
Info: Computing checksum on file /etc/puppetlabs/code/hiera.yaml
Info: FileBucket got a duplicate file {md5}38be16eebd05a89c2837135ab8dcec8b
Info: /Stage[main]/Puppet::Server::Config/File[/etc/puppetlabs/code/hiera.yaml]: Filebucketed /etc/puppetlabs/code/hiera.yaml to puppet with sum 38be16eebd05a89c2837135ab8dcec8b
Notice: /Stage[main]/Puppet::Server::Config/File[/etc/puppetlabs/code/hiera.yaml]/ensure: removed
Notice: /Stage[main]/Puppet::Agent::Service/Cron[puppet]/ensure: created
Info: Class[Puppet::Server::Config]: Scheduling refresh of Class[Puppet::Server::Service]
Info: Class[Puppet::Server::Service]: Scheduling refresh of Service[puppetserver]
Notice: /Stage[main]/Puppet::Server::Service/Service[puppetserver]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Puppet::Common/Concat[/etc/puppetlabs/puppet/puppet.conf]/File[/etc/puppetlabs/puppet/puppet.conf]/content:
--- /etc/puppetlabs/puppet/puppet.conf	2015-12-31 04:11:26.658107002 +0000
+++ /tmp/puppet-file20151231-21762-hlb2zc	2015-12-31 04:35:57.223163044 +0000
@@ -14,4 +14,3 @@

   always_cache_features = true
   ca = true
-  dns_alt_names = puppet,puppet.localdomain

Info: Computing checksum on file /etc/puppetlabs/puppet/puppet.conf
Info: /Stage[main]/Puppet::Common/Concat[/etc/puppetlabs/puppet/puppet.conf]/File[/etc/puppetlabs/puppet/puppet.conf]: Filebucketed /etc/puppetlabs/puppet/puppet.conf to puppet with sum 870603fba63a46639165d1b20ffb3223

**Comment by greigm** [comment]
Your hiera params should be set as follows:
puppet::params::dns_alt_names:
  - name1.example.org
  - name2.example.org
  - etc
puppet::params::manage_hiera: false

**Comment by jlambert121** [comment]
If you use the CLI hiera tool are values being returned correctly?  Hiera lookups with this module work fine form e as well, there should be no difference in how they work with this module as any other module.

**Comment by claflico** [comment]
I  still need to try it again since you said I needed to add ::params in my hiera variables. Most of the modules I work with just specify the class and variable name. I'll try to test it this weekend.

**Comment by jlambert121** [comment]
I don't think you need to add ::params to your variables - where did I say that?

**Comment by claflico** [comment]
My bad, it wasn't you. It was @greigm above.

**Comment by greigm** [comment]
@claflico Sorry, I might have steered you wrong there. I just realised that in my case, I'm merging functionality from several modules in one profile fragment, so I am specifically setting those params using hiera('param_name') and have used the params namespace to remind myself of that fact. I guess that logic doesn't work! ;) Anyway, I've just built a test setup, and can confirm that puppet::param_name works fine for this module. I suspect you have an issue with your hiera configuration.

**Comment by claflico** [comment]
Unfortunately I still am unable to get it to work. I have tried it both with and without "::params" in my hiera common.yaml file. 

I have created a vagrant file and a bootstrap script if either of you would be willing to take a look and tell me what I'm doing wrong. 

https://github.com/claflico/puppet-test-evenup

**Comment by greigm** [comment]
OK, I see the problem.

`
  if ( $server and $hiera_source and $manage_hiera) {
    file { '/etc/puppetlabs/code/hiera.yaml':
      source => $hiera_source,
    }
  } elsif $manage_hiera {
    file { '/etc/puppetlabs/code/hiera.yaml':
      ensure => 'absent',
    }
  }
`

So, if server is true, manage_hiera is true, and a hiera_source is provided, you're golden.
If ANY of those are false, but manage_hiera is true, your hiera.yaml file will be removed. This is probably not ideal.

To fix your scenario, I created /etc/puppetlabs/code/environments/production/modules/puppet/files/hiera.yaml (you would normally put this elsewhere - a profile file dir or something) with just basic per-env simple settings like so:

`---
:backends:
  - yaml
:yaml:
  :datadir: /etc/puppetlabs/code/environments/%{::environment}/hieradata
:hierarchy:
  - common
`

Then in common.yaml:

`---
puppet::server: true
puppet::runmode: 'service'
puppet::manage_hiera: true
puppet::hiera_source: 'puppet:///modules/puppet/hiera.yaml'
puppet::dns_alt_names:
 - 'puppet'
 - 'puppet.localdomain'`

And finally, in your manifest, I can just declare:

`class { 'puppet': }`

So... is it a bug? Perhaps. I see the logic. If we're supposed to manage hiera, but no source has been provided, we should probably ensure nothing else is trying to manage it by removing its config file. This should probably be more clearly documented in the README though. I choose you to submit a pull req. ;)

**Comment by claflico** [comment]
Between either the latest version of puppet or your module release, this appears to be working now. I'm able to read in hiera natively.
